# Generated by Django 5.0.7 on 2024-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seesion_year',
            name='session_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seesion_year',
            name='session_start',
            field=models.DateTimeField(),
        ),
    ]
