# Generated by Django 5.0.7 on 2024-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_seesion_year_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seesion_year',
            name='session_end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seesion_year',
            name='session_start',
            field=models.CharField(max_length=100),
        ),
    ]
