# Generated by Django 5.0.7 on 2024-12-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_student_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Notification',
            new_name='Staff_Notification',
        ),
    ]
